### ISSUE TITLE
Would you mind updating?

### ISSUE THREAD

**Issue by NeilGirdhar** [eiginn/netrw#17]
Released today: http://www.drchip.org/astronaut/vim/index.html#NETRW

**Comment by eiginn** [comment]
updated to v162d

**Comment by shaggyaxe** [comment]
Could I request an update to netrw v162j (or whatever the latest is when you read this)?

Thanks.  Much appreciated!

**Comment by eiginn** [comment]
updated

**Comment by shaggyaxe** [comment]
Thanks!  Much appreciated.
